name: CI Pipeline for GPT-Web

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install autopep8
      run: |
        pip install autopep8
      # Installs autopep8 for automatic code formatting

    - name: Format Python Code with autopep8
      run: |
        autopep8 --in-place --aggressive --aggressive .

    - name: Validate Vocabulary File
      run: |
        python -c "import json; json.load(open('vocab.json'))"
      # Ensures vocab.json is valid JSON

    - name: Lint Python Code
      run: |
        pip install flake8
        flake8 model.py
      # Checks for Python code style issues

    - name: Run Unit Tests
      run: |
        pip install pytest
        pytest tests/
      # Ensure your tests are in a 'tests/' folder and properly set up
